In [26]:
from typing import List

def transpose(matrix: List[List[int]]):
    n = len(matrix)
    for i in range(n):
        for j in range(i+1, n):
            matrix[i][j], matrix[j][i] = matrix[j][i], matrix[i][j]

class Solution:
    def rotate(self, matrix: List[List[int]]) -> None:
        transpose(matrix)
        n = len(matrix)
        for i in range(n):
            matrix[i].reverse()


In [27]:
import numpy


matrix = [[1,2,3],[4,5,6],[7,8,9]]
sol = Solution()
sol.rotate(matrix)
print(numpy.array(matrix))

[[7 4 1]
 [8 5 2]
 [9 6 3]]


In [28]:
matrix = [[5,1,9,11],[2,4,8,10],[13,3,6,7],[15,14,12,16]]
sol = Solution()
sol.rotate(matrix)
print(numpy.array(matrix))

[[15 13  2  5]
 [14  3  4  1]
 [12  6  8  9]
 [16  7 10 11]]
