In [61]:
%load_ext nb_mypy

The nb_mypy extension is already loaded. To reload it, use:
  %reload_ext nb_mypy


In [62]:
import numpy as np

In [63]:
from typing import List


class Solution:
    def setZeroes(self, matrix: List[List[int]]) -> None:
        """
        Space O(m + n), for storing aux arrays for marking whether the row or col is 0
        Time O(m * n)
        """
        rows = len(matrix)
        cols = len(matrix[0])
        rows0 = [False for i in range(rows)]
        cols0 = [False for i in range(cols)]

        for i in range(rows):
            for j in range(cols):
                if matrix[i][j] == 0:
                    rows0[i] = True
                    cols0[j] = True

        for i in range(rows):
            for j in range(cols):
                if rows0[i] or cols0[j]:
                    matrix[i][j] = 0


In [64]:
s = Solution()
matrix = [[0,1,2,0],[3,4,5,2],[1,3,1,5]]
print(np.matrix(matrix))
s.setZeroes(matrix)
print(np.matrix(matrix))

[[0 1 2 0]
 [3 4 5 2]
 [1 3 1 5]]
[[0 0 0 0]
 [0 4 5 0]
 [0 3 1 0]]


In [65]:
class Solution:
    def setZeroes(self, matrix: List[List[int]]) -> None:
        """
        Space O(1)
        Time O(m * n)
        """
        rows = len(matrix)
        cols = len(matrix[0])
        first_row_0 = False
        first_col_0 = False

        for i in range(rows):
            if matrix[i][0] == 0:
                first_col_0 = True

        for j in range(cols):
            if matrix[0][j] == 0:
                first_row_0 = True

        for i in range(1, rows):
            for j in range(1, cols):
                if matrix[i][j] == 0:
                    matrix[i][0] = matrix[0][j] = 0

        for i in range(1, rows):
            for j in range(1, cols):
                if matrix[i][0] == 0 or matrix[0][j] == 0:
                    matrix[i][j] = 0

        if first_row_0:
            for j in range(cols):
                matrix[0][j] = 0
        
        if first_col_0:
            for i in range(rows):
                matrix[i][0] = 0


In [66]:
s = Solution()
matrix = [[0,1,2,0],[3,4,5,2],[1,3,1,5]]
print(np.matrix(matrix))
s.setZeroes(matrix)
print(np.matrix(matrix))

[[0 1 2 0]
 [3 4 5 2]
 [1 3 1 5]]
[[0 0 0 0]
 [0 4 5 0]
 [0 3 1 0]]


In [67]:
s = Solution()
matrix = [[1,1,1],[1,0,1],[1,1,1]]
print(np.matrix(matrix))
s.setZeroes(matrix)
print(np.matrix(matrix))

[[1 1 1]
 [1 0 1]
 [1 1 1]]
[[1 0 1]
 [0 0 0]
 [1 0 1]]
