In [2146]:
from math_concepts import magic
import numpy as np

In [2147]:
magic.covariance_matrix(
    [
        [1, 0, -1, 3],
        [5, 5, -7, -3],
    ]
)

array([[  8.75,   3.  ],
       [  3.  , 108.  ]])

In [2148]:
from typing import List
chr(ord('a') + 1)

'b'

In [2149]:
22 * -26 + 9 * -11 + 2 * -2

-675

In [2150]:
def xt(t):
    return t**2 - 4
def yt(t):
    return 3 - t
xt(-1) * yt(-1) + xt(0) * yt(0) + xt(1) * yt(1)

-30

In [2151]:
magic.C(12, 5) * (6/10)**5 * (4/10) ** 7

0.10090237132800002

In [2152]:
magic.bernoulli_trial(12, 5, 6/10)

0.10090237132800002

In [2153]:
magic.binomial_distribution(10, 8, 10, 1/4)

0.000415802001953125

In [2154]:
magic.projxS([[0, 1], [-1, 0], [1, 1], [0, 0]], [0, 0, 3, 1])

array([ 1., -1.,  2.,  0.])

In [2155]:
np.array([5, 6, 4, -2]) - np.array([ 0.,  6.,  3., -3.])

array([5., 0., 1., 1.])

In [2156]:
np.linalg.norm(np.array([5, 6, 4, -2]) - np.array([ 0.,  6.,  3., -3.]))

5.196152422706632

In [2157]:
magic.projxS([[3, 3], [-3, -3], [-3, 3]], [0, 1, 0])

array([-5.00000000e-01,  5.00000000e-01,  2.77555756e-17])

In [2158]:
magic.anglexS([[0, 1], [1, 2], [2, 3]], [-1, -1, 2])

30.000000000000004

In [2159]:
np.pi / 4

0.7853981633974483

In [2160]:
magic.projxS([[-3, 3], [1, 0], [0, 1]], [-20, 5, -8])

array([-21.,   2.,  -5.])

In [2161]:
.0156 + .0938

0.1094

In [2162]:
.0156 + .0938

0.1094

In [2163]:
magic.least_squares_solution([[0, 2], [1, -1], [-1, 0], [2, 2]], [-5, 0, 1, 2])

array([ 1., -1.])

In [2164]:
A = np.array([[0, 2], [1, -1], [-1, 0], [2, 2]])
x_cap = np.array([ 1., -1.])
b = np.array([-5, 0, 1, 2])
np.linalg.norm(A@x_cap - b)

4.58257569495584

In [2165]:
10.677078252031311 * 10.677078252031311

114.0

In [2166]:
4.58257569495584 * 4.58257569495584

21.0

In [2167]:
A = np.array([[2, 4], [-1, -2], [1, 2]])
np.transpose(A) @ A

array([[ 6, 12],
       [12, 24]])

In [2168]:
A = np.array([[2, 4], [-1, -2], [1, 2]])
b = np.array([2, 0, 2])
np.transpose(A) @ b

array([ 6, 12])

In [2169]:
1/10 * (np.array([[11, -3], [-3, 1]]) @ np.array([22.8, 83.4]))

array([0.06, 1.5 ])

In [2170]:
.06 + 1.5 * 6

9.06

In [2171]:
(5.09 - 2) / 3

1.03

In [2172]:
(-.56 - 3) / 2

-1.78

In [2173]:
(4.73 - 2) / 3

0.9100000000000001

In [2174]:
1 - .8186

0.1814

In [2175]:
(3.78 - 5) / 2

-0.6100000000000001

In [2176]:
3.2 - .65*3

1.25

In [2177]:
4/.9192


4.351610095735422

In [2178]:
-3 + .75

-2.25

In [2179]:
2.25 / .75

3.0

In [2180]:
-2.2 - (-2)

-0.20000000000000018

In [2181]:
0.20000000000000018 / .2

1.0000000000000009

In [2182]:
8384/2

4192.0

In [2183]:
.4192 + .5

0.9192

In [2184]:
(4/1.4) ** 2

8.16326530612245

In [2185]:
.3328 / 2 + .5

0.6664

In [2186]:
(1.7 / .43) ** 2

15.630070308274743

In [2187]:
.2434/2

0.1217

In [2188]:
0.1217 + .5

0.6217

In [2189]:
4 * .31 / .7

1.7714285714285716

In [2190]:
.6318 / 2

0.3159

In [2191]:
magic.bernoulli_trial(6, 3, .6)

0.27648

In [2192]:
magic.binomial_distribution(6, 2, 4, .6)

0.72576

In [2193]:
-.81 + -.8

-1.61

In [2194]:
1.61/2

0.805

In [2195]:
(1.52 + 1.53) / 2

1.525

In [2196]:
from IPython.display import display, Math

# Display a LaTeX expression
display(Math(r'\int_a^b f(x) \, dx = F(b) - F(a)'))

<IPython.core.display.Math object>

In [2197]:
from sympy import symbols, diff

# Define the variable and the function
x = symbols('x')
y = symbols('y')
function = 2 * ((x + y + 1) ** (1/2))

# Calculate the derivative
derivative = diff(function, x)
print(derivative)
# print(derivative.sub)


1.0/(x + y + 1)**0.5


In [2198]:
from sympy import symbols, diff

def quadratic_taylor(function, x, a):
    """
    Compute the quadratic Taylor expansion of a function at a given point.
    
    Parameters:
    - function: The sympy expression representing the function.
    - x: The sympy symbol for the variable of the function.
    - a: The point at which the Taylor expansion is centered.

    Returns:
    - The quadratic Taylor expansion of the function.
    """
    # Compute the first derivative
    f_prime = diff(function, x)
    
    # Compute the second derivative
    f_double_prime = diff(f_prime, x)
    
    # Taylor expansion terms
    taylor_0 = function.subs(x, a)  # f(a)
    taylor_1 = f_prime.subs(x, a) * (x - a)  # f'(a) * (x - a)
    taylor_2 = f_double_prime.subs(x, a) * (x - a)**2 / 2  # f''(a) * (x - a)^2 / 2!
    
    # Combine terms
    taylor_expansion = taylor_0 + taylor_1 + taylor_2
    return taylor_expansion


In [2199]:
from sympy import Rational, Add

def convert_to_rational(expr):
    """
    Converts all numerical coefficients in a SymPy expression to rational numbers.
    
    Parameters:
        expr: sympy.Expr
            The input expression.
    
    Returns:
        sympy.Expr
            The expression with all numerical coefficients as Rational numbers.
    """
    if expr.is_Atom:  # Base case: if it's a single term
        if expr.is_Number:
            return Rational(expr)
        return expr

    if expr.is_Add or expr.is_Mul:  # If it's an addition or multiplication
        return expr.func(*[convert_to_rational(arg) for arg in expr.args])

    if expr.is_Pow:  # If it's a power
        base, exp = expr.args
        return base**convert_to_rational(exp)

    return expr  # Default case: return as is

# Example usage
from sympy import symbols

x, y = symbols('x y')
expr = -0.5 * x * y + 1.0 * x - 0.25 * y

# Convert to rational
rational_expr = convert_to_rational(expr)
print(rational_expr)


-x*y/2 + x - y/4


In [2200]:
from sympy import simplify, diff

def quadratic_taylor_multivariable(f, vars, point):
    """
    Compute the quadratic Taylor expansion of a multivariable function 
    at a given point.

    Parameters:
    - f:      The sympy expression representing the function.
    - vars:   A list of sympy symbols [x1, x2, ..., xn].
    - point:  A dict {x1: a1, x2: a2, ...} giving the expansion point.

    Returns:
    - The quadratic Taylor expansion of f about 'point', simplified.
    """

    # 0th-order term:  f(a)
    taylor = f.subs(point)

    # 1st-order terms:  sum of df/dx_i (a) * (x_i - a_i)
    for v in vars:
        df_dv = diff(f, v)
        taylor += df_dv.subs(point) * (v - point[v])

    # 2nd-order terms:
    #    1/2 \sum_{i,j} f_{i j}(a) * (x_i - a_i)(x_j - a_j)
    # A common way to avoid double counting is to loop i <= j:
    n = len(vars)
    for i in range(n):
        for j in range(i, n):
            d2 = diff(f, vars[i], vars[j]).subs(point)
            if i == j:
                # pure second derivative terms get a 1/2 factor
                taylor += d2 * (vars[i] - point[vars[i]])**2 / 2
            else:
                # cross terms appear once, but with no 1/2
                # (because f_{xy} = f_{yx} for sufficiently smooth f)
                taylor += d2 * (vars[i] - point[vars[i]]) * (vars[j] - point[vars[j]])

    return simplify(taylor)


In [2201]:
from sympy import symbols

# Define variables
x, y = symbols('x y')

# Define the function
function =2 * ((x + y + 1) ** (1/2))

# Center the expansion at (x=1, y=2)
point = {x: 0, y: 0}

# Compute the Taylor expansion
taylor_expansion = quadratic_taylor_multivariable(function, [x, y], point)
display(taylor_expansion)
display(convert_to_rational(taylor_expansion))


        2                           2            
- 0.25⋅x  - 0.5⋅x⋅y + 1.0⋅x - 0.25⋅y  + 1.0⋅y + 2

   2              2        
  x    x⋅y       y         
- ── - ─── + x - ── + y + 2
  4     2        4         

In [2202]:
from sympy import simplify, cos, sin
from sympy.abc import x, y
a = (x + x**2)/(x*sin(y)**2 + x*cos(y)**2)
a

        2            
       x  + x        
─────────────────────
     2           2   
x⋅sin (y) + x⋅cos (y)

In [2203]:
simplify(a)

x + 1

In [2204]:
from sympy import Rational

# Convert 0.25 to a fraction
fraction = Rational(0.25)
print(fraction)


1/4


In [2205]:
from sympy import symbols, Rational

# Define the variables
x, y = symbols('x y')

# Define the expression with Rational coefficients
expression = Rational(-0.5) * x * y + Rational(1.0) * x + Rational(-0.25) * y

print(expression)


-x*y/2 + x - y/4


In [2206]:
from sympy import init_printing, latex, symbols, Rational
init_printing()
# Define variables
x, y = symbols('x y')

# Example expression
expr = Rational(-1, 2) * x * y + x - Rational(1, 4) * y
display(expr)

  x⋅y       y
- ─── + x - ─
   2        4